### ISSUE TITLE
Connectivity status not accurate when page first loads

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/ceno#185] opened 2015-12-08 19:26 UTC
Reproduction steps:

1. Open the CENO portal.
2. Wait for the connectivity indicator to reflect the current status.
3. Navigate to a different page.

Expected results

The connectivity indicator continues to display the current status, and does not change unless the status changes

Actual results

The indicator always starts at "not connected" then updates to the correct status after ten seconds or more

**Comment by ivilata** [comment] 2016-07-12 10:25
In my case, I run CENO and as soon as the status shows CONNECTED, I open a different tab with a channel. However, while the channel loads, the indicator in the first tab seems to stay as CONNECTED, so I'm not able to reproduce the problem. Maybe the issue is already fixed in CENO 1.0?

**Comment by misaakidis** [comment] 2016-07-27 17:19
The issue has been fixed.
As an improvement, the status should be set while the page is getting generated via the templates (in the CENO Client golang code) and not by an independent request.

**Closed by misaakidis** 2016-07-27 17:19 UTC
Labels: bug
