### ISSUE TITLE
cenotransport dies with ENOENT error right after sending the POST request to the cacher server

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#25] opened 2015-02-25 16:23 UTC
Could it be that the bundler needs access to directories/files which do not exist? Could it be coming from the logger of the bundle? Or a local temporary storage?

Logs follow:
(www.google.fr has been  cached before)

-------------------

/usr/bin/node cenotransport.js
Initializing HTTP cache access with
cacheAddr = http://localhost:3091
bundlerAddr = http://localhost:3093
Successfully connected to : ./db
Successfully connected to : ./db
Client server listening on localhost:3090
Transport port number: 3093
Transport server listening on localhost:3093
Requesting http://localhost:3091/?url=http://www.google.fr succeeded.
Got bundle from cache server.
Requesting http://localhost:3091/?url=http://www.google.de succeeded.
Cache server does not have a bundle.
Got request to bundle http://www.google.de
Making bundler for http://www.google.de
Requesting http://localhost:3093/?url=http://www.google.de succeeded.
{ processID: 0 }
New process ID = 0
info: Applying diffs to HTML.
Sent post request to http://127.0.0.1:3092

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'log/info.log'

Process finished with exit code 8

**Comment by redwire** [comment] 2015-02-25 20:51
This one's really simple, actually. 
If you just read the actual error, `Error: ENOENT, open 'log/info.log'`, it's clear that the problem is that there's no entry to `log/info.log`.  The problem is just that you don't have a `log/` directory. I didn't realize it had been removed from the repository, but it can be fixed by running `mkdir log`.
Fixed in https://github.com/equalitie/ceno/commit/f25e6c237b199a26e1db07af6339ce0e809e6f8d

**Closed by redwire** 2015-02-25 20:51 UTC
