### ISSUE TITLE
CENO Portal's Visit a URL textbox is not redirecting to the proper link

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#171] opened 2015-11-27 22:09 UTC
As a user, I want to use CENO Portal's Visit a Website textbox to look for bundles.

Searching for www.google.com in the textbox opens a new tab to "http://localhost:3090/www.google.com"

**Comment by redwire** [comment] 2015-11-30 20:39
Sounds like you're blocking JS again.

**Comment by graphiclunarkid** [comment] 2015-12-01 19:18
We can't reproduce this. @misaakidis, please can you update this bug with reproduction steps, the expected result and the actual result you see. Alternatively, please close this if you can't reproduce it in a vanilla browser.

**Comment by misaakidis** [comment] 2015-12-01 19:45
I was using CENOBox's browser before, but can not replicate anymore.

**Comment by misaakidis** [comment] 2015-12-01 19:47
Actually I can still replicate, once the page refreshes I get the following error message:

You asked for http://localhost:3090/www.google.com
Here's the error we got: Requested URL is invalid

**Comment by graphiclunarkid** [comment] 2015-12-01 20:21
OK. Could you write down the exact steps you took to reproduce the bug? @redwire, if this is something you can look at before you leave, please can you commit it to the current sprint?

**Comment by misaakidis** [comment] 2015-12-01 20:36
Get CENOBox
./CENO.sh

In the new chrome window go to the respective text box and visit www.google.com
You get directed to a normal page "Your bundle is being prepared".
First refresh of the page though shows the "Requested URL is invalid" error.

Let me know if you would like me to provide you with the latest CENOBox.

**Comment by graphiclunarkid** [comment] 2015-12-01 22:11
The CENOBox build is not current. This needs testing on a client built from the tip of the "next" branch to confirm whether it's still a bug.

**Comment by misaakidis** [comment] 2015-12-02 14:40
Using the tip of the "next" branch, I am able to replicate the issue. The problem is somewhere on the redirection from an auto-refresh error page to a bundle lookup page.
If you would like to reproduce the issue please follow the steps in my previous comment.

**Closed** 2015-12-08 19:40 UTC
Labels: bug
